#!/usr/bin/env ruby

CJK = ['Noto Sans SC', 'Noto Sans TC', 'Noto Sans JP', 'Noto Sans KR', 'Noto Sans CJK', 'Noto Sans CJK SC', 'Noto Sans CJK TC', 'Noto Sans CJK JP', 'Noto Sans CJK KR', 'Noto Sans Mono CJK', 'Noto Sans Mono CJK SC', 'Noto Sans Mono CJK TC', 'Noto Sans Mono CJK JP', 'Noto Sans Mono CJK KR', 'Source Han Sans CN', 'Source Han Sans TW', 'Source Han Sans JP', 'Source Han Sans KR', 'Source Han Sans', 'Source Han Sans J', 'Source Han Sans K', 'Source Han Sans SC', 'Source Han Sans TC', 'Source Han Sans HW CN', 'Source Han Sans HW TW', 'Source Han Sans HW JP', 'Source Han Sans HW KR', 'Source Han Sans HW', 'Source Han Sans HW J', 'Source Han Sans HW K', 'Source Han Sans HW TC', 'Source Han Sans HW SC', 'Source Han Serif CN', 'Source Han Serif TW', 'Source Han Serif JP', 'Source Han Serif KR', 'Source Han Serif', 'Source Han Serif J', 'Source Han Serif K', 'Source Han Serif TC', 'Source Han Serif SC'].freeze

EMOJI = %w[Noto_Color_Emoji Noto_Emoji].freeze

hinted = open('noto-hinted.txt', 'r:UTF-8').read.split("\n")

non_hinted = open('noto-non-hinted.txt', 'r:UTF-8').read.split("\n")

fonts = hinted + non_hinted + CJK.map { |i| i.tr(' ', '_') } + EMOJI

puts '<?xml version="1.0"?>'
puts '<!DOCTYPE fontconfig SYSTEM "fonts.dtd">'
puts '<fontconfig>'
puts '  <!-- Do not edit it, generated by scripts/write_noto_default_family.rb -->'

fonts.each do |i|
  puts '  <alias>'
  puts "    <family>#{i.tr('_', ' ')}</family>"
  puts '    <default>'
  a = i.strip.split('_')
  if i.strip.end_with?('Symbols', 'Symbols2')
    puts '      <family>symbol</family>'
  elsif i.strip.end_with?('Emoji')
    puts '      <family>emoji</family>'
  elsif a[1] == 'Serif' || a[2] == 'Serif'
    puts '      <family>serif</family>'
  elsif a[1] == 'Mono' || a[2] == 'Mono' || a[3] == 'HW'
    puts '      <family>monospace</family>'
  else
    puts '      <family>sans-serif</family>'
  end
  puts '    </default>'
  puts '  </alias>'
end

puts '</fontconfig>'
